# Site Configuration
title: "Rupesh Purum - Data & AI Engineer"
name: "Rupesh Purum"
description: "Data & AI Engineer with 7 years experience in telecom, audio processing, and cloud data pipelines. Currently building media automation systems at Gangaji."

# Profile settings
profile_image: "assets/images/profile.jpg"
email: "rupeshpurum@gmail.com"
location: "Tampa, FL"

# External links (only add the ones you want to show)
external-links:
  linkedin: rupeshpurum  # https://www.linkedin.com/in/rupeshpurum
  github: rupeshpurum      # https://github.com/{your-username}

# GitHub Pages settings
remote_theme: pages-themes/cayman@v0.2.0 
plugins:
  - jekyll-feed
  - jekyll-sitemap


# Build settings
markdown: kramdown